services:
  app:
    build: .
    command: 'raspadmin web --gen-thumbnail'
    image: ghcr.io/mundotv789123/raspadmin-files-golang:latest
    ports:
      - "8080:8080"
    volumes:
      - ./files:/app/files
      - ./data:/app/data