name: Docker Image CI

on:
  push:
    branches: [ "main", "develop" ]

env:
  DOCKER_IMAGE_TAG: ghcr.io/mundotv789123/raspadmin-files-golang

jobs:
  docker-login:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set up environment docker tag
        id: set_env
        run: |
          if [[ "${{ github.ref_name }}" == "develop" ]]; then
            echo "DOCKER_IMAGE_TAG=${{ env.DOCKER_IMAGE_TAG }}:dev" >> $GITHUB_ENV
          fi
    
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to custom Docker registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

  docker-amd64:
    runs-on: ubuntu-latest
    needs: docker-login
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version: '1.26'
          check-latest: true
          cache-dependency-path: |
            subdir/go.sum
            tools/go.sum

      - name: go download
        run: go mod download

      - name: build amd64
        run: GIN_MODE=release GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o build/raspadmin main.go

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          file: Dockerfile
          context: .
          push: true
          tags: "${{ env.DOCKER_IMAGE_TAG }}"
          platforms: linux/amd64

  docker-arm64:
    runs-on: ubuntu-latest
    needs: docker-amd64
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version: '1.26'
          check-latest: true
          cache-dependency-path: |
            subdir/go.sum
            tools/go.sum

      - name: go download
        run: go mod download

      - name: build arm64
        run: GIN_MODE=release GOOS=linux GOARCH=arm64 go build -ldflags="-s -w" -o build/raspadmin main.go

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          file: Dockerfile
          context: .
          push: true
          tags: "${{ env.DOCKER_IMAGE_TAG }}"
          platforms: linux/arm64